export const COACH_TIPS: string[] = [
  "For a pour over, rinse your paper filter before brewing - it removes the papery taste and preheats your vessel.",
  "For a pour over, if your bloom barely bubbles, your coffee is stale. Fresh coffee releases visible CO₂.",
  "For a pour over, use water at 88–92°C for light roasts, not boiling - it preserves delicate floral notes.",
  "In an AeroPress, press into a preheated mug - cold mugs drop your brew temp by 5–8°C instantly.",
  "In an AeroPress, steep for just 1 minute - longer doesn't mean stronger, it means more bitter.",
  "In an AeroPress, use two filters instead of one for a dramatically cleaner, tea-like clarity in the cup.",
  "In a moka pot, keep the lid open while brewing - you'll know exactly when to pull it off heat.",
  "In a moka pot, never use soap - water only. The seasoned coating is flavor.",
  "In a moka pot, run the bottom chamber under cold water post-brew to stop residual heat from scorching.",
  "For cold brew, use a dark or medium roast - light roasts often taste sour and grassy when cold brewed.",
  "For cold brew, add a tiny pinch of salt to your concentrate - it rounds bitterness without adding flavor.",
  "For cold brew, add a strip of orange peel during steeping for a subtle, natural citrus lift.",
  "For filter kaapi, pack the coffee firmly but don't over-tamp - resistance slows the drip to a perfect pace.",
  "For filter kaapi, heat your milk to just before boiling - scalded milk kills the aroma.",
  "For filter kaapi, let the first few drops of decoction go - the initial drip is the most concentrated and bitter.",
  "In a French press, don't press all the way down - stop just below the surface to leave sediment undisturbed.",
  "In a French press, decant immediately after brewing - leaving it in the press keeps extracting and turns bitter.",
  "In a French press, try a 1:12 ratio instead of 1:15 for a richer, cafe-style body.",
  "Aim for water with a TDS of 100–150 ppm - too pure strips flavor, too hard mutes it.",
  "Add a single pinch of salt to black coffee to neutralise bitterness without making it taste salty.",
];
